server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: ${APPLICATION_NAME:configuration-service}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIGURATION_SOURCE_GIT:https://github.com/fdobrotv/cloud_config.git}
          cloneOnStart: true

eureka:
  instance:
    hostname: ${HOST_NAME:configuration-service-1.com}
    homePageUrl: http://${eureka.instance.hostname}/
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service-1.com:8761/eureka/}