replicaCount: 1
servicePort: 8888
containerPort: 8888
image:
  name: fdobrotv/configuration_service:0.3.3
  pullPolicy: IfNotPresent
app:
  name: configuration-service
  profile: dev,vault
  tracingServiceHost: tracing-service
  configurationSourceGit: https://github.com/fdobrotv/cloud_config.git
  vaultHost: 10.0.2.2 # virtualbox default gateway ( to access host machine from virtualbox )